# Generated by Django 5.0.3 on 2024-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cargues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargue",
            name="altoCaja",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cargue",
            name="altoContenedor",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cargue",
            name="anchoCaja",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cargue",
            name="anchoContenedor",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cargue",
            name="cantidadCajas",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cargue",
            name="largoCaja",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cargue",
            name="largoContenedor",
            field=models.IntegerField(),
        ),
    ]
